version: 2

jobs:
  test:
    parallelism: 1
    working_directory: ~/repo
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - restore_cache:
          key: repo-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "circle.yml" }}
      - run:
          name: Print versions
          command: |
            node --version
            npm --version
      - run: npm ci
      - save_cache:
          key: repo-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "circle.yml" }}
          paths:
            - ~/.npm
      - run: npm test
      - run: npm run size
      - run: npm run semantic-release || true

workflows:
  version: 2
  test:
    jobs:
      - test
